name: Rancher CLI for Github Actions
description: Use the Rancher CLI in github actions
author: dwene
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  token:
    description: Rancher Token for logging in.
    required: true
  context:
    description: Context of the project to access. (AKA Project ID)
    required: true
  url:
    description: URL of the Rancher instance.
    required: true
  command:
    description: Command you want to run.
    required: true
runs:
  using: docker
  image: docker://glacier3/rancher-cli:latest
