name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Rancher-Action-Example-Workflow
    runs-on: ubuntu-latest    
    steps:
      - name: Rancher CLI Action
        uses: roulianinc/Rancher-CLI@v1.0.2
        with:
          command: kubectl get pods -n warlock --insecure-skip-tls-verify
          token: ${{ secrets.RANCHER_TOKEN }}
          context: ${{ secrets.RANCHER_CONTEXT }}
          url: ${{ secrets.RANCHER_URL }}
